name: e_anamnez
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  firebase_auth: ^5.3.4
  fluttertoast: ^8.0.9
  random_string: ^2.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  shimmer_animation: ^2.2.1
  file_picker: ^8.1.3
  flutter_easyloading: ^3.0.5
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: ^0.18.0
  tflite_flutter: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/female.jpg
    - assets/images/male.jpg
    - assets/images/E_Anamnez.jpg
    - assets/model.tflite
    - assets/hastalik_tahmin_model.tflite
    

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf


    - family: Coolvetica
      fonts:
        - asset: assets/fonts/Coolvetica-rg.ttf
        - asset: assets/fonts/Coolvetica-rg-it.ttf
